# Generated by Django 2.0.3 on 2018-04-06 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0004_auto_20180331_1239'),
        ('clients', '0002_hireinvitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('payment_mode', models.CharField(choices=[('fixed', 'Fixed'), ('hourly', 'Hourly')], default='fixed', max_length=25, verbose_name='Payment Mode')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Start Date')),
                ('end_date', models.DateTimeField(null=True, verbose_name='End Date')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('blocked', 'Blocked')], default='pending', max_length=25, verbose_name='Project Status')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_client', to='clients.Client', verbose_name='Client')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_employee', to='employees.Employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
                'db_table': 'pms_contract',
            },
        ),
        migrations.CreateModel(
            name='ContractDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Document title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Document description')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('image', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d', verbose_name='Document')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_document', to='contracts.Contract', verbose_name='Contract')),
            ],
            options={
                'verbose_name': 'Contract Document',
                'verbose_name_plural': 'Contract Documents',
                'db_table': 'pms_contract_document',
                'ordering': ('title',),
            },
        ),
    ]
