# Generated by Django 2.0.3 on 2018-04-11 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0005_auto_20180412_0048'),
        ('clients', '0002_hireinvitation'),
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Last Updated Date')),
                ('first_name', models.CharField(blank=True, max_length=250, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=250, verbose_name='Last Name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email Address')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Phone Number')),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Zip Code')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('blocked', 'Blocked')], default='pending', max_length=25, verbose_name='Status')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.City')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_client', to='clients.Client')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.Country')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.State')),
            ],
            options={
                'verbose_name_plural': 'Clients Customers',
                'db_table': 'pms_clients_customers',
            },
        ),
        migrations.CreateModel(
            name='EmployeeProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Last Updated Date')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('allocation', models.FloatField(default=8.0, verbose_name='Allocated Hours')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_employee', to='employees.Employee')),
            ],
            options={
                'verbose_name_plural': 'Employee-Project Allocations',
                'db_table': 'pms_employees_projects',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Last Updated Date')),
                ('name', models.CharField(max_length=100, verbose_name='Project Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Project Description')),
                ('billing_method', models.CharField(choices=[('fixed_cost', 'Fixed Cost'), ('method_2', 'Method Two')], default='fixed_cost', max_length=25, verbose_name='Billing Method')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', max_length=25, verbose_name='Project Status')),
                ('estimation', models.CharField(blank=True, max_length=20, null=True, verbose_name='Effort Estimation')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_customer', to='projects.Customer')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_manager', to='employees.Employee')),
                ('members', models.ManyToManyField(blank=True, related_name='project_members', through='projects.EmployeeProject', to='employees.Employee')),
            ],
            options={
                'verbose_name_plural': 'Projects',
                'db_table': 'pms_clients_customers_project',
            },
        ),
        migrations.AddField(
            model_name='employeeproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_user_project', to='projects.Project'),
        ),
        migrations.AlterUniqueTogether(
            name='employeeproject',
            unique_together={('employee', 'project')},
        ),
    ]
