# Generated by Django 2.0.3 on 2018-04-20 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_auto_20180413_2318'),
        ('employees', '0005_auto_20180412_0048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Last Updated Date')),
                ('title', models.CharField(max_length=255, verbose_name='Task Title')),
                ('description', models.TextField(default='', null=True, verbose_name='Task Description')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('billing_method', models.CharField(choices=[('fixed_cost', 'Fixed Cost'), ('method_2', 'Method Two')], default='fixed_cost', max_length=25, verbose_name='Billing Method')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', max_length=25, verbose_name='Project Status')),
                ('effort', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Estimated Hours')),
                ('assign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assign', to='employees.Employee')),
            ],
            options={
                'verbose_name_plural': 'Project Tasks',
                'db_table': 'pms_tasks_task',
            },
        ),
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Last Updated Date')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Task Category')),
                ('description', models.TextField(default='', null=True)),
            ],
            options={
                'verbose_name_plural': 'Task Categories',
                'db_table': 'pms_tasks_category',
            },
        ),
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_category', to='tasks.TaskCategory'),
        ),
        migrations.AddField(
            model_name='task',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_creator', to='employees.Employee'),
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_project', to='projects.Project'),
        ),
    ]
