# Generated by Django 2.0.3 on 2018-04-13 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Last Updated Date')),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile/manager', verbose_name='Profile Image')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('transgender', 'Transgender')], default='male', max_length=25, verbose_name='Employee Gender')),
                ('first_name', models.CharField(blank=True, max_length=250, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=250, verbose_name='Last Name')),
                ('ssn', models.CharField(blank=True, max_length=50, verbose_name='Employee SSN')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Employee Date of Birth')),
                ('address_1', models.CharField(max_length=255, verbose_name='Address 1')),
                ('address_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address 2')),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Zip Code')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Employee Phone Number')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('blocked', 'Blocked')], default='pending', max_length=25, verbose_name='Employee Status')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.City')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.Country')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.State')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Project Manager',
                'db_table': 'pms_project_manager',
            },
        ),
    ]
