# Generated by Django 2.0.3 on 2018-04-14 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='address_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address 1'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.Country'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='first_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='last_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Last Name'),
        ),
    ]
