# Generated by Django 2.0.3 on 2018-03-27 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='City Name')),
            ],
            options={
                'verbose_name_plural': 'Manage Cities',
                'db_table': 'pms_masters_cities',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Country Name')),
                ('short_name', models.CharField(max_length=3, verbose_name='Country Short Name')),
                ('iso_3', models.CharField(blank=True, max_length=5, null=True, verbose_name='Country ISO3 Name')),
                ('phone_code', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Manage Countries',
                'db_table': 'pms_masters_countries',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='State Name')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.Country')),
            ],
            options={
                'verbose_name_plural': 'Manage States',
                'db_table': 'pms_masters_states',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.State'),
        ),
    ]
