# Generated by Django 2.0.3 on 2018-03-27 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bank', to='employees.Employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paycheck',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='paycheck', to='employees.Employee'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employmentcompensation',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensations', to='employees.Employee'),
        ),
    ]
