# Generated by Django 2.0.3 on 2018-03-31 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20180328_1947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employmentcompensation',
            old_name='is_currrent',
            new_name='is_current',
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(blank=True, max_length=250, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(blank=True, max_length=250, verbose_name='Last Name'),
        ),
    ]
