# Generated by Django 2.0.3 on 2018-04-11 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_auto_20180331_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='availability',
            field=models.CharField(choices=[('available', 'Available'), ('not_available', 'Not Available'), ('hired', 'Hired')], default='available', max_length=20, verbose_name='Employee Availability'),
        ),
    ]
